version: "3.9"

services:
  backend:
    build: .
    container_name: squad-backend
    command: gunicorn squad.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 2 --timeout 120
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8000:8000" # Django API on host:8000

  celery:
    build: .
    container_name: squad-celery
    command: celery -A squad worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

  # optional: celery beat (scheduler)
  celery-beat:
    build: .
    container_name: squad-celery-beat
    command: celery -A squad beat -l info
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:15
    container_name: squad-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "maintenance_work_mem=128MB"
      - "-c"
      - "effective_cache_size=512MB"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: squad-rabbitmq
    ports:
      - "5672:5672" # broker
      - "15672:15672" # management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
